DROP DATABASE IF EXISTS ESCUELA;
CREATE DATABASE ESCUELA;
USE ESCUELA;

CREATE TABLE Grado(
     cvegrado CHAR(1) PRIMARY KEY NOT NULL,
     nomgrupo VARCHAR(25) NOT NULL
);
CREATE TABLE Grupo(
     cveEsp CHAR(6) PRIMARY KEY NOT NULL,
     nomEsp VARCHAR(25) NOT NULL,
     cvegrado CHAR(1) NOT NULL,
     FOREIGN KEY (cvegrado)REFERENCES Grado (cvegrado)
                ON UPDATE CASCADE
);
INSERT INTO Grado VALUES('4','AMPG');
