DROP DATABASE IF EXISTS zapato;
CREATE DATABASE zapato;
USE zapato;

CREATE TABLE AREA(
     cveArea CHAR(1) PRIMARY KEY NOT NULL,
     nomArea VARCHAR(25) NOT NULL
);
CREATE TABLE ZAPATOS(
     cveEsp CHAR(6) PRIMARY KEY NOT NULL,
     nomEsp VARCHAR(25) NOT NULL,
     cveArea CHAR(1) NOT NULL,
     FOREIGN KEY (cveArea)REFERENCES AREA (cveArea)
                ON UPDATE CASCADE
);
INSERT INTO AREA VALUES('D','DEPORTIVO');
INSERT INTO AREA VALUES('E','ELEGANTES');
INSERT INTO AREA VALUES('C','CASUALES');